src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @var Tag[]
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="articles")
     */
    private $tags;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $thumb;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="article")
     */
    private $comments;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $DatePublication;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Heading", inversedBy="articles")
     */
    private $heading;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ImageGallery", mappedBy="article")
     */
    private $imageGalleries;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->tags = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->active = false;
        $this->imageGalleries = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return Tag[]|null
     */
    public function getTagArticle(): ?Collection
    {
        return $this->tags;
    }

    public function addTagArticle(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTagArticle(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getThumb(): ?string
    {
        return $this->thumb;
    }

    public function setThumb(string $thumb): self
    {
        $this->thumb = $thumb;

        return $this;
    }

    public function toArray()
    {
        return [
            'id' => $this->getId(),
            'title' => $this->getTitle(),
            'thumb' => $this->getThumb(),
            'description' => $this->getDescription(),
            'content' => $this->getContent(),
            'heading' => $this->getHeading()->getId() ?? 0
        ];
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->DatePublication;
    }

    public function setDatePublication(?\DateTimeInterface $DatePublication): self
    {
        $this->DatePublication = $DatePublication;

        return $this;
    }

    public function setComments($comments)
    {
        $this->comments = $comments;
        return $this;
    }

    public function getHeading(): ?Heading
    {
        return $this->heading;
    }

    public function setHeading(?Heading $heading): self
    {
        $this->heading = $heading;

        return $this;
    }

    public function setActive($active): self
    {
        $this->active = $active;
        return $this;
    }


    public function getActive()
    {
        return $this->active;
    }

    /**
     * @return Collection|ImageGallery[]
     */
    public function getImageGalleries(): Collection
    {
        return $this->imageGalleries;
    }

    public function addImageGallery(ImageGallery $imageGallery): self
    {
        if (!$this->imageGalleries->contains($imageGallery)) {
            $this->imageGalleries[] = $imageGallery;
            $imageGallery->setArticle($this);
        }

        return $this;
    }

    public function removeImageGallery(ImageGallery $imageGallery): self
    {
        if ($this->imageGalleries->contains($imageGallery)) {
            $this->imageGalleries->removeElement($imageGallery);
            // set the owning side to null (unless already changed)
            if ($imageGallery->getArticle() === $this) {
                $imageGallery->setArticle(null);
            }
        }

        return $this;
    }


}

src/Controller/Site/ArticleController.php
<?php
namespace App\Controller\Site;

use App\Controller\BaseController;
use App\Entity\Article;
use App\Entity\ImageGallery;
use App\Repository\ArticleRepository;
use App\Repository\HeadingRepository;
use App\Repository\TagRepository;
use App\Service\ServiceFileUpload;
use Doctrine\Common\Persistence\ObjectManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ArticleController
 * @package App\Controller\Site
 * @Route("article")
 *
 */
class ArticleController extends BaseController
{

    /**
     * @Route("/", name="site_article_index")
     * @return Response
     */
    public function indexAction()
    {
        return $this->render("site/article/index.html.twig");
    }

    /**
     * @Route("/moderation/no-publication", name="site_article_noPublication")
     * @param Request $request
     * @param ArticleRepository $articleRepository
     * @return Response
     */
    public function noPublicationAction(
        Request $request,
        ArticleRepository $articleRepository
    )
    {
        return $this->render("site/main/index.html.twig", [
            'title' => 'статьи на модерацию',
            'articles'  => $this->getPaginatorArticles(false, $request, $articleRepository),
        ]);
    }

    /**
     * @Route("/{id}/show", name="site_article_show")
     * @param ArticleRepository $articleRepository
     * @return Response
     */
    public function showAction(ArticleRepository $articleRepository, $id)
    {
        return $this->render("site/article/show.html.twig", [
            'article' => $articleRepository->find(intval($id))
        ]);
    }

    /**
     * @Route("/moderation/create", name="site_article_create")
     * @param HeadingRepository $headingRepository
     * @param TagRepository $tagRepository
     * @return Response
     */
    public function createAction(
        HeadingRepository $headingRepository,
        TagRepository $tagRepository
    )
    {
        $headings = $headingRepository->findAll();
        $tags = $tagRepository->findAll();
        return $this->render("site/article/create.html.twig", [
            'headings' => $headings,
            'tags' => $tags,
        ]);
    }

    /**
     * @Route("/moderation/add", name="site_article_add")
     * @param Request $request
     * @param ObjectManager $manager
     * @param HeadingRepository $headingRepository
     * @param TagRepository $tagRepository
     * @return Response
     */
    public function addAction(
        Request $request,
        ObjectManager $manager,
        HeadingRepository $headingRepository,
        TagRepository $tagRepository
    )
    {
        $status = true;
        $message = null;
        $thumbName = null;
        $lastId = null;
        $fileDirName = $this->getParameter('article_directory');

        $manager->getConnection()->beginTransaction();

        try {

            if (!$request->isXmlHttpRequest()) {
                throw new \Exception("Это не ajax", 007);
            }

            $formData = $request->get("formData");
            $thumbData = $request->get("thumbData");

            if (!empty($thumbData)) {
                $file = new ServiceFileUpload($thumbData[0]);
                $thumbName = $file->upload($fileDirName);
            }

            $heading = $headingRepository->find($formData['heading']);
            $tags = $tagRepository->findSelectIdTags($formData['tags']);

            $article = new Article();

            $article
                ->setUser($this->getUser())
                ->setTitle($formData["title"])
                ->setThumb($thumbName ?? "")
                ->setDescription($formData['description'])
                ->setContent($formData['content'])
                ->setHeading($heading)
                ->setDatePublication(null)
            ;

            if ($tags) {
                foreach ($tags as $tag) {
                    $tag->addArticle($article);
                    $manager->persist($tag);
                    $article->addTagArticle($tag);
                }
            }

            $manager->persist($article);
            $manager->flush();

            $lastId = $article->getId();

            $message = "Статья - " . $article->getTitle() . " добавлена.";

            $manager->commit();


        } catch (\Exception $e) {
            $manager->getConnection()->rollBack();

            if ($thumbName) {
                $fullPath = $fileDirName . "/" . $thumbName;

                if (file_exists($fullPath)) {
                    unlink($fullPath);
                }
            }

            $status = false;
            $message = $e->getMessage();
        }

        return new JsonResponse([
            'status' => $status,
            'message' => $message,
            'lastId' => $lastId
        ]);
    }

    /**
     * @Route("/moderation/{id}/publication", name="site_article_publication")
     * @param Request $request
     * @param ArticleRepository $articleRepository
     * @param ObjectManager $manager
     * @param $id
     * @return JsonResponse
     */
    public function publicationAction(
        Request $request,
        ArticleRepository $articleRepository,
        ObjectManager $manager,
        $id
    )
    {
        $status = true;
        $message = null;
        $dateTime = new \DateTime();

        $article = $articleRepository->find(intval($id));

        try {

            $publication = $request->get("publication");

            if ($publication) {
                $dateTime = new \DateTime($publication);

            }

            if (!$article) {
                throw new \Exception("Запись не найдена.");
            }

            if (!$this->getUser()) {
                throw new \Exception("Сначало надо авторизоваться ", 007);
            }

            $article->setActive(true);
            $article->setDatePublication($dateTime);
            $manager->persist($article);
            $manager->flush();

            $message = "Запись успешно опубликована дата назначена ".$publication;

        } catch (\Exception $e) {
            $status = false;
            $message = $e->getMessage();
        }

        return new JsonResponse([
            'status' => $status,
            'message' => $message
        ]);
    }

    /**
     * @Route("/upload_image", name="site_article_upload_image")
     * @Method({"POST"})
     * @param Request $request
     * @param ArticleRepository $articleRepository
     * @param ObjectManager $manager
     * @return Response
     */
    public function uploadGalleryAction(
        Request $request,
        ArticleRepository $articleRepository,
        ObjectManager $manager
    )
    {
        $status = true;
        $message = null;
        $imageName = null;

        $fileDirName = $this->getParameter('image_gallery_directory');

        try {

            $imageData = $request->get('data');
            $id = $request->get('id_item');

            if (!$imageData) {
                throw new \Exception("файл не был передан.");
            }

            $article = $articleRepository->find(intval($id));

            if (!$article) {
                throw new \Exception("Запись не найдена");
            }

            $file = new ServiceFileUpload($imageData);
            $imageName = $file->upload($fileDirName);

            if (!$imageName) {
                throw new \Exception("Ошибка загрузки файла.");
            }

            $gallery = new ImageGallery();

            $gallery
                ->setArticle($article)
                ->setName($imageName)
            ;

            $manager->persist($gallery);
            $manager->flush();

        } catch (\Exception $e) {
            $status = false;
            $message = $e->getMessage();
        }

        return new JsonResponse([
            'status' => $status,
            'message' => $message
        ]);
    }


}

src/Controller/Site/HeadingController.php
<?php

namespace App\Controller\Site;

use App\Controller\BaseController;
use App\Repository\ArticleRepository;
use App\Repository\HeadingRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class HeadingController
 * @package App\Controller\Site
 * @Route("heading")
 */
class HeadingController extends BaseController
{
    /**
     * @Route("/{id}", name="site_heading_index")
     * @param ArticleRepository $articleRepository
     * @param HeadingRepository $headingRepository
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction(
        ArticleRepository $articleRepository,
        HeadingRepository $headingRepository,
        Request $request,
        $id
    )
    {
        $heading = $headingRepository->find(intval($id));

        return $this->render("site/main/index.html.twig", [
            'articles'  => $this->getPaginatorArticles(true, $request, $articleRepository, $heading),
            'title' => 'Список новостей'
        ]);
    }

}

src/Controller/Site/TagController.php
<?php

namespace App\Controller\Site;

use App\Controller\BaseController;
use App\Repository\ArticleRepository;
use App\Repository\TagRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class HeadingController
 * @package App\Controller\Site
 * @Route("tag")
 */
class TagController extends BaseController
{
    /**
     * @Route("/{id}", name="site_tag_index")
     * @param ArticleRepository $articleRepository
     * @param TagRepository $tagRepository
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction(
        ArticleRepository $articleRepository,
        TagRepository $tagRepository,
        Request $request,
        $id
    )
    {
        $tags = $tagRepository->find(intval($id));

        return $this->render("site/main/index.html.twig", [
            'articles'  => $this->getPaginatorArticles(true, $request, $articleRepository, null, $tags),
            'title' => 'Список новостей'
        ]);
    }

}

templates/site/article/create.html.twig
{% extends 'layouts/site.layout.html.twig' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="section-content">
                <div class="content-head">
                    <h4 class="content-title">Добавление статьи</h4><!-- /.content-title -->
                </div><!-- /.content-head -->
                <form action="{{ path('site_article_add') }}" method="post" id="form-article" enctype="multipart/form-data" class="form-horizontal">
                    {{ include('site/article/form/formField.html.twig', {'headings' : headings, 'tags' : tags, 'btnName' : 'Добавить'}) }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block javaScript %}

    <script>
        $(document).ready(function() {

            $(".standardSelect").chosen({
                disable_search_threshold: 10,
                no_results_text: "Ой, ничего не найдено!",
                width: "100%"
            });

            let thumb = new JqueryImageUploader({
                mainBlockName: ".content-thumb",
                maxFiles: 1,
                thumb: true
            });

            thumb.init();

            let gallery = new JqueryImageUploader({
                urlUploadImage: '{{ path('site_article_upload_image') }}',
                mainBlockName: ".content-gallery",
                maxFiles: 10
            });

            gallery.init();

            $("#form-article").submit(function (e) {
                e.preventDefault();

                let $btn = $(this).find("button[type=submit]");
                let formData = {};
                let $fields = $(this).find("input, textarea, select");
                let $categoryMessage = $(".article-message");

                $btn.attr("disabled", true);
                $fields.each(function() {
                    let value = $(this).val();

                    if (this.name === 'active') {
                        value = $(this).prop("checked");
                    }

                    formData[this.name] = value;
                });

                $.post($(this).attr("action"), {formData:formData, thumbData:thumb.dataArray})
                    .done(function (response) {
                        if (response.status) {

                            gallery.uploadLoadingItemImg(response.lastId, function () {
                                window.location.href = "{{ path('site_main_index') }}";
                            });

                            $categoryMessage
                                .removeClass("alert-danger")
                                .addClass("show")
                                .addClass("alert-success")
                                .html(response.message);

                            setInterval(function () {
                                window.location.href = "{{ path('site_main_index') }}";
                            }, 2000);
                        } else {
                            $categoryMessage
                                .removeClass("alert-success")
                                .addClass("show")
                                .addClass("alert-danger")
                                .html(response.message);

                            $btn.attr("disabled", false);
                        }
                    })
                    .fail(function (reason) {
                        $categoryMessage
                            .removeClass("alert-success")
                            .addClass("show")
                            .addClass("alert-danger")
                            .html(reason.responseText);
                        $btn.attr("disabled", false);
                        console.log(reason);
                    })
                ;

            });
        });
    </script>
{% endblock %}

templates/site/article/index.html.twig
{% extends "layouts/site.layout.html.twig" %}

{% block content %}
    <h1>Список новосте</h1>
{% endblock %}

templates/site/article/show.html.twig
{% extends 'layouts/site.layout.html.twig' %}

{% block content %}
<!-- post content -->
<div class="content-box">

    {% if article %}

    <!-- standard post -->
    <article class="entry mb-0">

        {% if is_granted('ROLE_ADMIN') %}
            {% if not article.active %}
                <input type="text" class="publishDate publishDate" placeholder="Выберите дату публикации" dataformatas="dd/MM/yyyy">
                <a href="{{ path('site_article_publication', {'id' : article.id}) }}" class="btn-publishDate-article"><button class="btn btn-lg btn-color">Опубликовать</button></a>
                <hr>
            {% endif %}
        {% endif %}

        <div class="single-post__entry-header entry__header">
            Рубрика:
            <a href="{{ path('site_heading_index', {'id' : article.heading.id}) }}" class="entry__meta-category entry__meta-category--label entry__meta-category--green">{{ article.heading.name }}</a>
            <h1 class="single-post__entry-title">
                {{ article.title }}
            </h1>

            <div class="entry__meta-holder">
                <ul class="entry__meta">
                    {% if article.datePublication %}
                        <li>
                            <span>Дата публикации:</span>
                            <a href="#">{{ article.datePublication.format("d-m-Y H:i:s") }}</a>
                        </li>
                    {% endif %}
                    <li>
                        <span>Дата создания:</span>
                        <a href="#">{{ article.createdAt.format("d-m-Y H:i:s") }}</a>
                    </li>
                </ul>

                <ul class="entry__meta">
                    <li class="entry__meta-views">
                        <i class="ui-eye"></i>
                        <span>0</span>
                    </li>
                    <li class="entry__meta-comments">
                        <a href="#">
                            <i class="ui-chat-empty"></i>{{ article.comments.count }}
                        </a>
                    </li>
                </ul>
            </div>
        </div> <!-- end entry header -->

        <div class="entry__img-holder">
            <img src="{{ asset(article_directory~article.thumb) }}" alt="" class="entry__img">
        </div>

        <div class="entry__article-wrap">

            <div class="entry__article">
                <p>{{ article.content }}</p>

                {% if article.imageGalleries  %}
                    {% for gallery in article.imageGalleries %}
                        <div class="entry__img-holder">
                            <img src="{{ asset(image_gallery_directory~gallery.name) }}" alt="" class="entry__img">
                        </div>
                    {% endfor %}
                {% endif %}

                <!-- tags -->
                <div class="entry__tags">
                    <i class="ui-tags"></i>
                    <span class="entry__tags-label">Теги:</span>
                    {% if article.tagArticle %}
                        {% for tag in article.tagArticle %}
                            <a href="{{ path('site_tag_index', {'id' : tag.id}) }}" rel="tag">{{ tag.name }}</a>
                        {% endfor %}
                    {% endif %}
                </div> <!-- end tags -->

            </div> <!-- end entry article -->
        </div> <!-- end entry article wrap -->

        <!-- Author -->
        <div class="entry-author clearfix">
            <img alt="" data-src="/assets/img/content/single/author.jpg" src="/assets/img/empty.png" class="avatar lazyload">
            <div class="entry-author__info">
                <h6 class="entry-author__name">
                    Автор: <a href="#">{{ article.user.email }}</a>
                </h6>
            </div>
        </div>

    </article> <!-- end standard post -->

    <!-- Comments -->
    <div class="entry-comments">
        <div class="title-wrap title-wrap--line">
            <h3 class="section-title">Коментарии</h3>
        </div>
        <ul class="comment-list">
            {% for comment in article.comments %}
                {{ include('site/comment/list.html.twig', {'comment' : comment}) }}
            {% endfor %}
        </ul>
    </div> <!-- end comments -->

    <!-- Comment Form -->
    <div id="respond" class="comment-respond">
        <div class="title-wrap">
            <h5 class="comment-respond__title section-title">Оставить коментарий</h5>
        </div>
        <form id="form-comment" class="comment-form" method="post" action="{{ path('site_comment_add', {'id' : article.id}) }}">
            <p class="comment-form-comment">
                <label for="comment">Коментарий</label>
                <textarea id="comment" name="content" rows="5" required="required"></textarea>
            </p>
            <p class="comment-form-submit">
                <button type="submit" class="btn btn-lg btn-color btn-button" >Коментировать</button>
            </p>
            <hr>
            <p class="comment-form-comment">
                <div class="alert alert-dismissible fade comment-message" role="alert"></div>
            </p>
        </form>
    </div> <!-- end comment form -->

    {% else %}
        <h3>Статья не найдена</h3>
    {% endif %}

</div> <!-- end content box -->
{% endblock %}
{% block javaScript %}

    <script>
        $(document).ready(function() {

            let publishDate = $('.publishDate');
            publishDate.datepicker({
                dateFormat: 'dd/mm/yy'
            });


            $(document).on("click", ".delete-comment", function (e) {
                e.preventDefault();

               let href = $(this).attr("href");
               let id = $(this).attr("data-id");

                $.post(href)
                    .done(function (response) {
                        if (response.status) {
                            alert(response.message);
                            $(".comment-id-"+id).remove();
                        } else {
                           alert(response.message);
                        }
                    })
                    .fail(function (reason) {
                        alert(reason.message);
                    })
                ;
            });

            $(document).on("click", ".btn-publishDate-article", function (e) {
                e.preventDefault();

               let href = $(this).attr("href");
               let publication = $(".publishDate").val();

                $.post(href, {"publication":publication})
                    .done(function (response) {
                        if (response.status) {
                            alert(response.message);
                            window.location.href = "{{ path('site_article_show', {'id' : article.id}) }}";
                        } else {
                           alert(response.message);
                        }
                    })
                    .fail(function (reason) {
                        alert(reason.message);
                    })
                ;
            });


            $("#form-comment").submit(function (e) {
                e.preventDefault();

                let $btn = $(this).find("input[type=submit]");
                let formData = {};
                let $fields = $(this).find("input, textarea, select");
                let $commentMessage = $(".comment-message");

                $btn.attr("disabled", true);
                $fields.each(function() {
                    let value = $(this).val();

                    if (this.name === 'active') {
                        value = $(this).prop("checked");
                    }

                    formData[this.name] = value;
                });

                $.post($(this).attr("action"), {formData:formData})
                    .done(function (response) {
                        if (response.status) {
                            $commentMessage
                                .removeClass("alert-danger")
                                .addClass("show")
                                .addClass("alert-success")
                                .html(response.message);

                            $fields.each(function() {
                                $(this).val("");
                            });
                            $(".comment-list").append(response.commentContent);
                        } else {
                            $commentMessage
                                .removeClass("alert-success")
                                .addClass("show")
                                .addClass("alert-danger")
                                .html(response.message);

                            $btn.attr("disabled", false);
                        }
                    })
                    .fail(function (reason) {
                        $commentMessage
                            .removeClass("alert-success")
                            .addClass("show")
                            .addClass("alert-danger")
                            .html(reason.responseText);
                        $btn.attr("disabled", false);
                        console.log(reason);
                    })
                ;

            });
        });
    </script>
{% endblock %}